# Generated by Django 5.0 on 2025-08-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_salaryrecord_unpaid_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='unpaid_leave',
            field=models.IntegerField(default=0, verbose_name='Unpaid Leave(Days)'),
        ),
    ]
